# Generated by Django 4.2.16 on 2024-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default='Sin introducción', max_length=255),
        ),
    ]
